[features]
resolution = true
skip-lint = false

#[programs.localnet]
#zeitgeist = "4mtjVwJ3h3zEffFbgZaNHShFywhaepAXyAkT2uEHYQuF"


[programs.devnet]
zeitgeist = "4mtjVwJ3h3zEffFbgZaNHShFywhaepAXyAkT2uEHYQuF"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "cargo test"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
#upgradeable = true